package constants

const (
	LogRequestStarted     = "request started"
	LogRequestCompleted   = "request completed"
	LogAuthRegister       = "User registration requested"
	LogAuthLogin          = "User login requested"
	LogUserProfileRead    = "User profile read"
	LogUserProfileUpdated = "User profile updated"
	LogMoodCreated        = "Mood created with mood_level and mood_tags"
	LogMoodListed         = "Mood list requested"
	LogMoodUpdated        = "Mood updated"
	LogMoodDeleted        = "Mood deleted"
	LogMoodTrend          = "Mood trend calculated"
	LogAssessmentListed   = "Assessment list requested"
	LogAssessmentCreated  = "Assessment created"
	LogAssessmentTaken    = "Assessment submitted"
	LogAssessmentResult   = "Assessment result generated"
	LogJournalCreated     = "Journal created"
	LogJournalListed      = "Journal list requested"
	LogJournalUpdated     = "Journal updated"
	LogJournalDeleted     = "Journal deleted"
	LogAuditWrite         = "audit write action"
	LogDBConnected        = "database connected"
	LogDBMigrated         = "database migrated"
	LogHealthChecked      = "health check completed"
	LogErrorWrapped       = "application error wrapped"
	LogSeeded             = "sample assessments seeded"
	LogFollowUpScheduled  = "FollowUp scheduled for next-day check-in"
	LogFollowUpMerged     = "FollowUp merged with existing same-day record"
	LogFollowUpRevoked    = "FollowUp revoked after mood level recovered"
	LogFollowUpReopened   = "FollowUp reopened after low mood recorded again"
	LogFollowUpListed     = "FollowUp list requested"
	LogFollowUpResponded  = "FollowUp result submitted by owner"
	LogFollowUpDuplicate  = "FollowUp duplicate submission ignored"
	LogFollowUpReconciled = "FollowUp reconciled after mood change"
)
