import {Button,Card,Checkbox,Col,Form,Input,Row,Select,Slider,Tag,Typography,message} from 'antd';import {useEffect,useMemo,useState} from 'react';import {deleteJournal,listJournals,saveJournal} from '../api/journal';import {listCheckIns} from '../api/checkin';import {EmptyState} from '../components/common/EmptyState';import {MoodCard} from '../components/common/MoodCard';import {CheckInCard} from '../components/common/CheckInCard';import {CheckInReminder} from '../components/common/CheckInReminder';import {useCheckIns} from '../hooks/useCheckIns';import type {Journal,MoodCheckIn} from '../types';
export function Journals(){
  const [items,setItems]=useState<Journal[]>([]),[allCheckIns,setAllCheckIns]=useState<MoodCheckIn[]>([]);
  const {duePending:dueCheckIns,submitting,load:loadDue,respond:respondCheckIn}=useCheckIns({status:'pending'});
  // 日记页关联当日回访：优先按低落触发日（trigger_date）与日记日期匹配。
  const checkInByDay=useMemo(()=>{const m=new Map<string,MoodCheckIn>();for(const c of allCheckIns){const d=c.trigger_date.slice(0,10);if(!m.has(d))m.set(d,c)}return m},[allCheckIns]);
  const load=()=>Promise.all([listJournals(),listCheckIns(),loadDue()]).then(([js,cs])=>{setItems(js);setAllCheckIns(cs)}).catch(e=>message.error(e.message));
  useEffect(()=>{load()},[]);
  const handleRespond=async(id:number,result:'improved'|'still_troubled')=>{const r=await respondCheckIn(id,result);if(r.ok){message.success('回访结果已记录');load()}else{message.error(r.error.message||'回访已有结果，只保留第一条')}};
  return <><Typography.Title>日记本</Typography.Title>
  <CheckInReminder pending={dueCheckIns} submitting={submitting} onRespond={handleRespond}/>
  <Row gutter={[20,20]}><Col xs={24} lg={10}><Card title="写一页日记"><Form layout="vertical" initialValues={{mood_level:7,is_private:true,weather:'晴'}} onFinish={async v=>{try{await saveJournal(v);message.success('日记已保存');load()}catch(e){message.error((e as Error).message)}}}><Form.Item name="title" label="标题" rules={[{required:true}]}><Input placeholder="给今天一句标题"/></Form.Item><Form.Item name="content" label="正文（支持 Markdown 风格文本）" rules={[{required:true}]}><Input.TextArea rows={8} placeholder="今天发生了什么？"/></Form.Item><Form.Item name="mood_level" label="心情指数"><Slider min={1} max={10}/></Form.Item><Form.Item name="weather" label="天气"><Select options={['晴','阴','雨','风'].map(v=>({value:v}))}/></Form.Item><Form.Item name="is_private" valuePropName="checked"><Checkbox>仅自己可见</Checkbox></Form.Item><Button type="primary" htmlType="submit">保存日记</Button></Form></Card></Col>
  <Col xs={24} lg={14}><Card title="时间轴">{items.length?<div className="timeline">{items.map(j=>{const day=j.created_at.slice(0,10);const linked=checkInByDay.get(day);return <article className="journal" key={j.id}><div><Tag color="purple">{day}</Tag><b>{j.title}</b><span className="muted"> · {j.weather} · 心情 {j.mood_level}/10</span></div><p>{j.content}</p>{linked&&<div className="journal-checkin"><CheckInCard compact checkIn={linked}/></div>}<Button danger size="small" onClick={async()=>{await deleteJournal(j.id);message.success('已删除');load()}}>删除</Button><div className="journal-mood"><MoodCard mood={{id:j.id,user_id:0,mood_level:j.mood_level,mood_tags:'["calm"]',note:'日记中的情绪',record_date:j.created_at,created_at:j.created_at}}/></div></article>})}</div>:<EmptyState title="写下第一篇日记，和自己好好聊聊"/>}</Card></Col></Row></>}
