import {Button,Card,Col,DatePicker,Form,Input,Row,Slider,Typography,message} from 'antd';import dayjs from 'dayjs';import {useEffect,useState} from 'react';import {listMoods,saveMood} from '../api/mood';import {MoodCard} from '../components/common/MoodCard';import {MoodSelector} from '../components/common/MoodSelector';import {CheckInCard} from '../components/common/CheckInCard';import {CheckInReminder} from '../components/common/CheckInReminder';import {EmptyState} from '../components/common/EmptyState';import {useCheckIns} from '../hooks/useCheckIns';import type {Mood,MoodTag} from '../types';
export function Moods(){
  const [moods,setMoods]=useState<Mood[]>([]),[tags,setTags]=useState<MoodTag[]>(['happy']),[date,setDate]=useState<string>();
  const {duePending:dueCheckIns,submitting:checkInSubmitting,load:loadDue,respond:respondCheckIn}=useCheckIns({status:'pending'});
  // 按筛选日期关联当日触发的回访（含已撤销/已确认的历史闭环状态）；仅在选择日期后请求。
  const {checkIns:dateCheckIns}=useCheckIns({triggerDate:date,auto:!!date});
  const load=()=>Promise.all([listMoods(date),loadDue()]).then(([m])=>setMoods(m)).catch(e=>message.error(e.message));
  useEffect(()=>{load()},[date]);
  const handleRespond=async(id:number,result:'improved'|'still_troubled')=>{const r=await respondCheckIn(id,result);if(r.ok){message.success('回访结果已记录');load()}else{message.error(r.error.message||'回访已有结果，只保留第一条')}};
  return <><Typography.Title>情绪记录</Typography.Title>
  <CheckInReminder pending={dueCheckIns} submitting={checkInSubmitting} onRespond={handleRespond}/>
  <Card className="filter-bar"><DatePicker placeholder="按日期筛选" onChange={v=>setDate(v?.format('YYYY-MM-DD'))}/><Button onClick={()=>setDate(undefined)}>清除筛选</Button></Card>
  <Row gutter={[20,20]}><Col xs={24} lg={9}><Card title="新增一条记录"><Form layout="vertical" initialValues={{level:6,date:dayjs()}} onFinish={async v=>{try{await saveMood({mood_level:v.level,mood_tags:tags,note:v.note||'',record_date:v.date.format('YYYY-MM-DD'),source:'moods'});message.success(v.level<=3?'已保存，明天会来回访你':'已保存');load()}catch(e){message.error((e as Error).message)}}}><Form.Item name="date" label="日期"><DatePicker style={{width:'100%'}}/></Form.Item><Form.Item name="level" label="心情指数"><Slider min={1} max={10}/></Form.Item><Form.Item label="情绪标签"><MoodSelector value={tags} onChange={setTags}/></Form.Item><Form.Item name="note" label="备注"><Input.TextArea rows={3}/></Form.Item><Button type="primary" htmlType="submit">保存记录</Button></Form></Card></Col>
  <Col xs={24} lg={15}><Card title={`记录列表 (${moods.length})`}>{dateCheckIns.length>0&&<div className="card-list checkin-linked">{dateCheckIns.map(c=><CheckInCard key={c.id} checkIn={c}/>)}</div>}{moods.length?<div className="card-list">{moods.map(m=><MoodCard key={m.id} mood={m}/>)}</div>:<EmptyState title="还没有符合条件的情绪记录"/>}</Card></Col></Row></>}
